In [36]:
import numpy as np
import pandas as pd

In [37]:
match = pd.read_csv('match_info_data.csv')
delivery = pd.read_csv('match_complete_data.csv',low_memory=False)

In [38]:
match.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1370353,2023,Ahmedabad,2023/05/29,Gujarat Titans,Chennai Super Kings,Chennai Super Kings,field,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
1,1370352,2023,Ahmedabad,2023/05/26,Gujarat Titans,Mumbai Indians,Mumbai Indians,field,normal,0,Gujarat Titans,62,0,Shubman Gill,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,J Madanagopal
2,1370351,2023,Chennai,2023/05/24,Mumbai Indians,Lucknow Super Giants,Mumbai Indians,bat,normal,0,Mumbai Indians,81,0,Akash Madhwal,"MA Chidambaram Stadium, Chepauk, Chennai",BNJ Oxenford,VK Sharma,CB Gaffaney
3,1370350,2023,Chennai,2023/05/23,Chennai Super Kings,Gujarat Titans,Gujarat Titans,field,normal,0,Chennai Super Kings,15,0,RD Gaikwad,"MA Chidambaram Stadium, Chepauk, Chennai",AK Chaudhary,CB Gaffaney,BNJ Oxenford
4,1359543,2023,Mumbai,2023/05/21,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,8,C Green,"Wankhede Stadium, Mumbai",KN Ananthapadmanabhan,RJ Tucker,R Pandit

In [39]:
match.shape

(1024, 18)

In [40]:
delivery.head()

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,cricsheet_id
0,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.1,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353
1,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.2,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353
2,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.3,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353
3,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.4,Gujarat Titans,Chennai Super Kings,Shubman Gill,WP Saha,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353
4,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.5,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353

In [41]:
delivery.shape

(243817, 23)

In [42]:
# Group by 'match_id' and 'innings' and sum only 'runs_off_bat' and 'extras'
total_score_df = delivery.groupby(['match_id', 'innings']).sum()[['runs_off_bat', 'extras']].reset_index()

In [43]:
# Calculate the total score by summing 'runs_off_bat' and 'extras'
total_score_df['total_score'] = total_score_df['runs_off_bat'] + total_score_df['extras']

In [44]:
# Add 1 run to the total score
total_score_df['total_score'] += 1

In [45]:
# Display the resulting DataFrame
total_score_df

      match_id  innings  runs_off_bat  extras  total_score
0       335982        1           205      17          223
1       335982        2            63      19           83
2       335983        1           234       6          241
3       335983        2           196      11          208
4       335984        1           122       7          130
...        ...      ...           ...     ...          ...
2070   1370351        2            91      10          102
2071   1370352        1           223      10          234
2072   1370352        2           164       7          172
2073   1370353        1           210       4          215
2074   1370353        2           166       5          172

[2075 rows x 5 columns]

In [46]:
# Filter for only the first innings
total_score_df = total_score_df[total_score_df['innings'] == 1]

In [47]:
total_score_df

      match_id  innings  runs_off_bat  extras  total_score
0       335982        1           205      17          223
2       335983        1           234       6          241
4       335984        1           122       7          130
6       335985        1           154      11          166
8       335986        1           100      10          111
...        ...      ...           ...     ...          ...
2065   1359544        1           190       7          198
2067   1370350        1           167       5          173
2069   1370351        1           166      16          183
2071   1370352        1           223      10          234
2073   1370353        1           210       4          215

[1024 rows x 5 columns]

In [48]:
#merging this total_score column based on match_id to match_info_data
match_df = match.merge(total_score_df[['match_id','total_score']],left_on='id',right_on='match_id')

In [49]:
match_df

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id,total_score
0,1370353,2023,Ahmedabad,2023/05/29,Gujarat Titans,Chennai Super Kings,Chennai Super Kings,field,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,1370353,215
1,1370352,2023,Ahmedabad,2023/05/26,Gujarat Titans,Mumbai Indians,Mumbai Indians,field,normal,0,Gujarat Titans,62,0,Shubman Gill,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,J Madanagopal,1370352,234
2,1370351,2023,Chennai,2023/05/24,Mumbai Indians,Lucknow Super Giants,Mumbai Indians,bat,normal,0,Mumbai Indians,81,0,Akash Madhwal,"MA Chidambaram Stadium, Chepauk, Chennai",BNJ Oxenford,VK Sharma,CB Gaffaney,1370351,183
3,1370350,2023,Chennai,2023/05/23,Chennai Super Kings,Gujarat Titans,Gujarat Titans,field,normal,0,Chennai Super Kings,15,0,RD Gaikwad,"MA Chidambaram Stadium, Chepauk, Chennai",AK Chaudhary,CB Gaffaney,BNJ Oxenford,1370350,173
4,1359543,2023,Mumbai,2023/05/21,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,8,C Green,"Wankhede Stadium, Mumbai",KN Ananthapadmanabhan,RJ Tucker,R Pandit,1359543,201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1019,335986,2007/08,Kolkata,2008/04/20,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,normal,0,Kolkata Knight Riders,0,5,DJ Hussey,Eden Gardens,BF Bowden,K Hariharan,Asad Rauf,335986,111
1020,335985,2007/08,Mumbai,2008/04/20,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,normal,0,Royal Challengers Bangalore,0,5,MV Boucher,Wankhede Stadium,SJ Davis,DJ Harper,AV Jayaprakash,335985,166
1021,335984,2007/08,Delhi,2008/04/19,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,normal,0,Delhi Daredevils,0,9,MF Maharoof,Feroz Shah Kotla,Aleem Dar,GA Pratapkumar,IL Howell,335984,130
1022,335983,2007/08,Chandigarh,2008/04/19,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,normal,0,Chennai Super Kings,33,0,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",MR Benson,SL Shastri,RB Tiffin,335983,241
1023,335982,2007/08,Bangalore,2008/04/18,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,AM Saheba,335982,223

In [50]:
match_df['team1'].unique()

array(['Gujarat Titans', 'Mumbai Indians', 'Chennai Super Kings',
       'Sunrisers Hyderabad', 'Royal Challengers Bangalore',
       'Lucknow Super Giants', 'Punjab Kings', 'Delhi Capitals',
       'Kolkata Knight Riders', 'Rajasthan Royals', 'Kings XI Punjab',
       'Delhi Daredevils', 'Rising Pune Supergiant', 'Gujarat Lions',
       'Rising Pune Supergiants', 'Pune Warriors', 'Deccan Chargers',
       'Kochi Tuskers Kerala'], dtype=object)

In [51]:
teams = [
    'Mumbai Indians',
    'Chennai Super Kings',
    'Royal Challengers Bangalore',
    'Kings XI Punjab',
    'Kolkota Knight Riders',
    'Sunrisers Hyderabad',
    'Rajasthan Royals',
    'Delhi Capitals',
    'Gujarat Titans',
    'Lucknow Super Giants'
]

In [52]:
match_df['team1'] = match_df['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team2'] = match_df['team2'].str.replace('Delhi Daredevils','Delhi Capitals')

match_df['team1'] = match_df['team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['team2'] = match_df['team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

match_df['team1'] = match_df['team1'].str.replace('Gujarat Lions','Gujarat Titans')
match_df['team2'] = match_df['team2'].str.replace('Gujarat Lions','Gujarat Titans')

match_df['team1'] = match_df['team1'].str.replace('Punjab Kings','Kings XI Punjab')
match_df['team2'] = match_df['team2'].str.replace('Punjab Kings','Kings XI Punjab')

In [53]:
match_df = match_df[match_df['team1'].isin(teams)]
match_df = match_df[match_df['team2'].isin(teams)]

In [54]:
match_df.shape

(709, 20)

In [55]:
match_df = match_df[match_df['dl_applied'] == 0]

In [56]:
match_df = match_df[['match_id','city','winner','total_score']]

In [57]:
match_df

      match_id        city                       winner  total_score
1      1370352   Ahmedabad               Gujarat Titans          234
2      1370351     Chennai               Mumbai Indians          183
3      1370350     Chennai          Chennai Super Kings          173
4      1359543      Mumbai               Mumbai Indians          201
5      1359544   Bengaluru               Gujarat Titans          198
...        ...         ...                          ...          ...
1017    335988   Hyderabad             Delhi Daredevils          143
1018    335987      Jaipur             Rajasthan Royals          167
1020    335985      Mumbai  Royal Challengers Bangalore          166
1021    335984       Delhi             Delhi Daredevils          130
1022    335983  Chandigarh          Chennai Super Kings          241

[700 rows x 4 columns]

In [58]:
delivery_df = match_df.merge(delivery,on='match_id')

In [59]:
delivery_df = delivery_df[delivery_df['innings'] == 2]

In [60]:
delivery_df.shape

(81420, 26)

In [61]:
delivery_df

,match_id,city,winner,total_score,season,start_date,venue,innings,ball,batting_team,...,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,cricsheet_id
127,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.1,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352
128,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.2,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352
129,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.3,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352
130,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.4,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352
131,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.5,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,caught,N Wadhera,NaN,NaN,1370352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168138,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,19.2,Kings XI Punjab,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335983
168139,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,19.3,Kings XI Punjab,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335983
168140,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,19.4,Kings XI Punjab,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335983
168141,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,19.5,Kings XI Punjab,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335983
168142,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,19.6,Kings XI Punjab,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335983

In [62]:
# Calculate cumulative sums of 'runs_off_bat' and 'extras' within each group of 'match_id'
#delivery_df['cumulative_runs_off_bat'] = delivery_df.groupby('match_id')['runs_off_bat'].cumsum()
#delivery_df['cumulative_extras'] = delivery_df.groupby('match_id')['extras'].cumsum()

# Combine both cumulative sums
#delivery_df['current_score'] = delivery_df['cumulative_runs_off_bat'] + delivery_df['cumulative_extras']

#we can simply do this instead of abaove
delivery_df['current_score'] = delivery_df.groupby('match_id').apply(
    lambda x: (x['runs_off_bat'] + x['extras']).cumsum()
).reset_index(level=0, drop=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_10348\1475875151.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  delivery_df['current_score'] = delivery_df.groupby('match_id').apply(

In [63]:
delivery_df

,match_id,city,winner,total_score,season,start_date,venue,innings,ball,batting_team,...,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,cricsheet_id,current_score
127,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.1,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,0
128,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.2,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,1
129,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.3,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,1
130,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.4,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,5
131,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.5,Mumbai Indians,...,NaN,NaN,NaN,NaN,caught,N Wadhera,NaN,NaN,1370352,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168138,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,19.2,Kings XI Punjab,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335983,200
168139,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,19.3,Kings XI Punjab,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335983,200
168140,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,19.4,Kings XI Punjab,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335983,206
168141,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,19.5,Kings XI Punjab,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335983,207
168142,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,19.6,Kings XI Punjab,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335983,207

In [64]:
# Filter for specific 'match_id' and 'innings'
filtered_df = delivery_df[(delivery_df['match_id'] == 1370352) & (delivery_df['innings'] == 2)]

In [65]:
filtered_df

,match_id,city,winner,total_score,season,start_date,venue,innings,ball,batting_team,...,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,cricsheet_id,current_score
127,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.1,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,0
128,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.2,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,1
129,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.3,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,1
130,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.4,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,5
131,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.5,Mumbai Indians,...,NaN,NaN,NaN,NaN,caught,N Wadhera,NaN,NaN,1370352,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,17.4,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,166
238,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,17.5,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,170
239,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,17.6,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,170
240,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,18.1,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,171
241,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,18.2,Mumbai Indians,...,NaN,NaN,NaN,NaN,caught,K Kartikeya,NaN,NaN,1370352,171

In [66]:
delivery_df['runs_left'] = delivery_df['total_score'] - delivery_df['current_score']

In [67]:
delivery_df

,match_id,city,winner,total_score,season,start_date,venue,innings,ball,batting_team,...,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,cricsheet_id,current_score,runs_left
127,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.1,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,0,234
128,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.2,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,1,233
129,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.3,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,1,233
130,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.4,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,5,229
131,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.5,Mumbai Indians,...,NaN,NaN,NaN,caught,N Wadhera,NaN,NaN,1370352,5,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168138,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,19.2,Kings XI Punjab,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335983,200,41
168139,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,19.3,Kings XI Punjab,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335983,200,41
168140,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,19.4,Kings XI Punjab,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335983,206,35
168141,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,19.5,Kings XI Punjab,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335983,207,34
168142,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,19.6,Kings XI Punjab,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335983,207,34

In [68]:
# Filter for specific 'match_id' and 'innings'
filtered_df = delivery_df[(delivery_df['match_id'] == 1370352) & (delivery_df['innings'] == 2)]
filtered_df

,match_id,city,winner,total_score,season,start_date,venue,innings,ball,batting_team,...,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,cricsheet_id,current_score,runs_left
127,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.1,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,0,234
128,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.2,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,1,233
129,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.3,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,1,233
130,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.4,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,5,229
131,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.5,Mumbai Indians,...,NaN,NaN,NaN,caught,N Wadhera,NaN,NaN,1370352,5,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,17.4,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,166,68
238,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,17.5,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,170,64
239,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,17.6,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,170,64
240,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,18.1,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,171,63
241,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,18.2,Mumbai Indians,...,NaN,NaN,NaN,caught,K Kartikeya,NaN,NaN,1370352,171,63

In [73]:
# Calculate over and ball components from the ball column
delivery_df['over'] = delivery_df['ball'].astype(int)
delivery_df['ball_in_over'] = (delivery_df['ball'] * 10 % 10).astype(int)

# Calculate total balls bowled so far
delivery_df['total_balls_bowled'] = delivery_df['over'] * 6 + delivery_df['ball_in_over']

# Calculate balls left
delivery_df['balls_left'] = 121 - delivery_df['total_balls_bowled']

In [74]:
delivery_df

,match_id,city,winner,total_score,season,start_date,venue,innings,ball,batting_team,...,player_dismissed,other_wicket_type,other_player_dismissed,cricsheet_id,current_score,runs_left,over,ball_in_over,total_balls_bowled,balls_left
127,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.1,Mumbai Indians,...,NaN,NaN,NaN,1370352,0,234,0,1,-5,125
128,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.2,Mumbai Indians,...,NaN,NaN,NaN,1370352,1,233,0,2,-4,124
129,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.3,Mumbai Indians,...,NaN,NaN,NaN,1370352,1,233,0,3,-3,123
130,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.4,Mumbai Indians,...,NaN,NaN,NaN,1370352,5,229,0,4,-2,122
131,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.5,Mumbai Indians,...,N Wadhera,NaN,NaN,1370352,5,229,0,5,-1,121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168138,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,19.2,Kings XI Punjab,...,NaN,NaN,NaN,335983,200,41,19,1,109,11
168139,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,19.3,Kings XI Punjab,...,NaN,NaN,NaN,335983,200,41,19,3,111,9
168140,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,19.4,Kings XI Punjab,...,NaN,NaN,NaN,335983,206,35,19,3,111,9
168141,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,19.5,Kings XI Punjab,...,NaN,NaN,NaN,335983,207,34,19,5,113,7
168142,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,19.6,Kings XI Punjab,...,NaN,NaN,NaN,335983,207,34,19,6,114,6