In [148]:
import numpy as np
import pandas as pd

In [149]:
match = pd.read_csv('match_info_data.csv')
delivery = pd.read_csv('match_complete_data.csv',low_memory=False)

In [150]:
match.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1370353,2023,Ahmedabad,2023/05/29,Gujarat Titans,Chennai Super Kings,Chennai Super Kings,field,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
1,1370352,2023,Ahmedabad,2023/05/26,Gujarat Titans,Mumbai Indians,Mumbai Indians,field,normal,0,Gujarat Titans,62,0,Shubman Gill,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,J Madanagopal
2,1370351,2023,Chennai,2023/05/24,Mumbai Indians,Lucknow Super Giants,Mumbai Indians,bat,normal,0,Mumbai Indians,81,0,Akash Madhwal,"MA Chidambaram Stadium, Chepauk, Chennai",BNJ Oxenford,VK Sharma,CB Gaffaney
3,1370350,2023,Chennai,2023/05/23,Chennai Super Kings,Gujarat Titans,Gujarat Titans,field,normal,0,Chennai Super Kings,15,0,RD Gaikwad,"MA Chidambaram Stadium, Chepauk, Chennai",AK Chaudhary,CB Gaffaney,BNJ Oxenford
4,1359543,2023,Mumbai,2023/05/21,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,8,C Green,"Wankhede Stadium, Mumbai",KN Ananthapadmanabhan,RJ Tucker,R Pandit

In [151]:
match.shape

(1024, 18)

In [152]:
delivery.head()

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,cricsheet_id
0,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.1,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353
1,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.2,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353
2,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.3,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353
3,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.4,Gujarat Titans,Chennai Super Kings,Shubman Gill,WP Saha,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353
4,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.5,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353

In [153]:
delivery.shape

(243817, 23)

In [154]:
# Group by 'match_id' and 'innings' and sum only 'runs_off_bat' and 'extras'
total_score_df = delivery.groupby(['match_id', 'innings']).sum()[['runs_off_bat', 'extras']].reset_index()

In [155]:
# Calculate the total score by summing 'runs_off_bat' and 'extras'
total_score_df['total_score'] = total_score_df['runs_off_bat'] + total_score_df['extras']

In [156]:
# Add 1 run to the total score
total_score_df['total_score'] += 1

In [157]:
# Display the resulting DataFrame for both innings
total_score_df.head()

   match_id  innings  runs_off_bat  extras  total_score
0    335982        1           205      17          223
1    335982        2            63      19           83
2    335983        1           234       6          241
3    335983        2           196      11          208
4    335984        1           122       7          130

In [158]:
# Filter for only the first innings
total_score_df = total_score_df[total_score_df['innings'] == 1]

In [159]:
total_score_df.head()

   match_id  innings  runs_off_bat  extras  total_score
0    335982        1           205      17          223
2    335983        1           234       6          241
4    335984        1           122       7          130
6    335985        1           154      11          166
8    335986        1           100      10          111

In [160]:
#merging this total_score column based on match_id to match_info_data
match_df = match.merge(total_score_df[['match_id','total_score']],left_on='id',right_on='match_id')

In [161]:
match_df.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id,total_score
0,1370353,2023,Ahmedabad,2023/05/29,Gujarat Titans,Chennai Super Kings,Chennai Super Kings,field,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,1370353,215
1,1370352,2023,Ahmedabad,2023/05/26,Gujarat Titans,Mumbai Indians,Mumbai Indians,field,normal,0,Gujarat Titans,62,0,Shubman Gill,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,J Madanagopal,1370352,234
2,1370351,2023,Chennai,2023/05/24,Mumbai Indians,Lucknow Super Giants,Mumbai Indians,bat,normal,0,Mumbai Indians,81,0,Akash Madhwal,"MA Chidambaram Stadium, Chepauk, Chennai",BNJ Oxenford,VK Sharma,CB Gaffaney,1370351,183
3,1370350,2023,Chennai,2023/05/23,Chennai Super Kings,Gujarat Titans,Gujarat Titans,field,normal,0,Chennai Super Kings,15,0,RD Gaikwad,"MA Chidambaram Stadium, Chepauk, Chennai",AK Chaudhary,CB Gaffaney,BNJ Oxenford,1370350,173
4,1359543,2023,Mumbai,2023/05/21,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,8,C Green,"Wankhede Stadium, Mumbai",KN Ananthapadmanabhan,RJ Tucker,R Pandit,1359543,201

In [162]:
match_df['team1'].unique()

array(['Gujarat Titans', 'Mumbai Indians', 'Chennai Super Kings',
       'Sunrisers Hyderabad', 'Royal Challengers Bangalore',
       'Lucknow Super Giants', 'Punjab Kings', 'Delhi Capitals',
       'Kolkata Knight Riders', 'Rajasthan Royals', 'Kings XI Punjab',
       'Delhi Daredevils', 'Rising Pune Supergiant', 'Gujarat Lions',
       'Rising Pune Supergiants', 'Pune Warriors', 'Deccan Chargers',
       'Kochi Tuskers Kerala'], dtype=object)

In [163]:
teams = [
    'Mumbai Indians',
    'Chennai Super Kings',
    'Royal Challengers Bangalore',
    'Kings XI Punjab',
    'Kolkota Knight Riders',
    'Sunrisers Hyderabad',
    'Rajasthan Royals',
    'Delhi Capitals',
    'Gujarat Titans',
    'Lucknow Super Giants'
]

In [164]:
match_df['team1'] = match_df['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team2'] = match_df['team2'].str.replace('Delhi Daredevils','Delhi Capitals')

match_df['team1'] = match_df['team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['team2'] = match_df['team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

match_df['team1'] = match_df['team1'].str.replace('Gujarat Lions','Gujarat Titans')
match_df['team2'] = match_df['team2'].str.replace('Gujarat Lions','Gujarat Titans')

match_df['team1'] = match_df['team1'].str.replace('Punjab Kings','Kings XI Punjab')
match_df['team2'] = match_df['team2'].str.replace('Punjab Kings','Kings XI Punjab')

In [165]:
match_df = match_df[match_df['team1'].isin(teams)]
match_df = match_df[match_df['team2'].isin(teams)]

In [166]:
match_df.shape

(709, 20)

In [167]:
#extracting only match with no dl_applied
match_df = match_df[match_df['dl_applied'] == 0]

In [168]:
match_df = match_df[['match_id','city','winner','total_score']]

In [169]:
match_df.head()

   match_id       city               winner  total_score
1   1370352  Ahmedabad       Gujarat Titans          234
2   1370351    Chennai       Mumbai Indians          183
3   1370350    Chennai  Chennai Super Kings          173
4   1359543     Mumbai       Mumbai Indians          201
5   1359544  Bengaluru       Gujarat Titans          198

In [170]:
delivery_df = match_df.merge(delivery,on='match_id')

In [171]:
delivery_df = delivery_df[delivery_df['innings'] == 2]

In [172]:
delivery_df.shape

(81420, 26)

In [173]:
delivery_df.head()

,match_id,city,winner,total_score,season,start_date,venue,innings,ball,batting_team,...,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,cricsheet_id
127,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.1,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352
128,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.2,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352
129,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.3,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352
130,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.4,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352
131,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.5,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,caught,N Wadhera,NaN,NaN,1370352

In [174]:
# Calculate cumulative sums of 'runs_off_bat' and 'extras' within each group of 'match_id'
#delivery_df['cumulative_runs_off_bat'] = delivery_df.groupby('match_id')['runs_off_bat'].cumsum()
#delivery_df['cumulative_extras'] = delivery_df.groupby('match_id')['extras'].cumsum()

# Combine both cumulative sums
#delivery_df['current_score'] = delivery_df['cumulative_runs_off_bat'] + delivery_df['cumulative_extras']

#we can simply do this instead of abaove
delivery_df['current_score'] = delivery_df.groupby('match_id').apply(
    lambda x: (x['runs_off_bat'] + x['extras']).cumsum()
).reset_index(level=0, drop=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_18400\1475875151.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  delivery_df['current_score'] = delivery_df.groupby('match_id').apply(

In [175]:
delivery_df.head()

,match_id,city,winner,total_score,season,start_date,venue,innings,ball,batting_team,...,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,cricsheet_id,current_score
127,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.1,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,0
128,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.2,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,1
129,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.3,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,1
130,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.4,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,5
131,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.5,Mumbai Indians,...,NaN,NaN,NaN,NaN,caught,N Wadhera,NaN,NaN,1370352,5

In [176]:
# Filter for specific 'match_id' and 'innings'
filtered_df = delivery_df[(delivery_df['match_id'] == 1370352) & (delivery_df['innings'] == 2)]

In [177]:
filtered_df

,match_id,city,winner,total_score,season,start_date,venue,innings,ball,batting_team,...,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,cricsheet_id,current_score
127,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.1,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,0
128,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.2,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,1
129,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.3,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,1
130,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.4,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,5
131,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.5,Mumbai Indians,...,NaN,NaN,NaN,NaN,caught,N Wadhera,NaN,NaN,1370352,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,17.4,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,166
238,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,17.5,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,170
239,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,17.6,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,170
240,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,18.1,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,171
241,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,18.2,Mumbai Indians,...,NaN,NaN,NaN,NaN,caught,K Kartikeya,NaN,NaN,1370352,171

In [178]:
delivery_df['runs_left'] = delivery_df['total_score'] - delivery_df['current_score']

In [179]:
delivery_df.head()

,match_id,city,winner,total_score,season,start_date,venue,innings,ball,batting_team,...,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,cricsheet_id,current_score,runs_left
127,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.1,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,0,234
128,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.2,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,1,233
129,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.3,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,1,233
130,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.4,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,5,229
131,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.5,Mumbai Indians,...,NaN,NaN,NaN,caught,N Wadhera,NaN,NaN,1370352,5,229

In [180]:
# Filter for specific 'match_id' and 'innings'
filtered_df = delivery_df[(delivery_df['match_id'] == 1370352) & (delivery_df['innings'] == 2)]
filtered_df

,match_id,city,winner,total_score,season,start_date,venue,innings,ball,batting_team,...,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,cricsheet_id,current_score,runs_left
127,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.1,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,0,234
128,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.2,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,1,233
129,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.3,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,1,233
130,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.4,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,5,229
131,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,0.5,Mumbai Indians,...,NaN,NaN,NaN,caught,N Wadhera,NaN,NaN,1370352,5,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,17.4,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,166,68
238,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,17.5,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,170,64
239,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,17.6,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,170,64
240,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,18.1,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370352,171,63
241,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,18.2,Mumbai Indians,...,NaN,NaN,NaN,caught,K Kartikeya,NaN,NaN,1370352,171,63

In [181]:
# Extract over and ball number from the ball column
delivery_df['over'] = delivery_df['ball'].astype(int)+1
delivery_df['ball'] = (delivery_df['ball'] * 10 % 10).astype(int)

# Cap the number of overs to 20
delivery_df = delivery_df[delivery_df['over'] < 20]

In [182]:
delivery_df

,match_id,city,winner,total_score,season,start_date,venue,innings,ball,batting_team,...,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,cricsheet_id,current_score,runs_left,over
127,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,1,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,1370352,0,234,1
128,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,2,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,1370352,1,233,1
129,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,3,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,1370352,1,233,1
130,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,4,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,NaN,1370352,5,229,1
131,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,5,Mumbai Indians,...,NaN,NaN,caught,N Wadhera,NaN,NaN,1370352,5,229,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168132,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,2,Kings XI Punjab,...,NaN,NaN,NaN,NaN,NaN,NaN,335983,193,48,19
168133,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,3,Kings XI Punjab,...,NaN,NaN,NaN,NaN,NaN,NaN,335983,194,47,19
168134,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,4,Kings XI Punjab,...,NaN,NaN,NaN,NaN,NaN,NaN,335983,195,46,19
168135,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,5,Kings XI Punjab,...,NaN,NaN,NaN,NaN,NaN,NaN,335983,197,44,19
168136,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,6,Kings XI Punjab,...,NaN,NaN,NaN,NaN,NaN,NaN,335983,198,43,19

In [183]:
delivery_df.to_csv("new_data_with_over.csv", index=False)

In [184]:
delivery_df['balls_left'] = 126 - (delivery_df['over']*6 + delivery_df['ball'])

In [185]:
delivery_df.head()

,match_id,city,winner,total_score,season,start_date,venue,innings,ball,batting_team,...,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,cricsheet_id,current_score,runs_left,over,balls_left
127,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,1,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,1370352,0,234,1,119
128,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,2,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,1370352,1,233,1,118
129,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,3,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,1370352,1,233,1,117
130,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,4,Mumbai Indians,...,NaN,NaN,NaN,NaN,NaN,1370352,5,229,1,116
131,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,5,Mumbai Indians,...,NaN,caught,N Wadhera,NaN,NaN,1370352,5,229,1,115

In [186]:
#player_dismissed tell if batsman was out or not while playing that ball
#filling null values with 0
delivery_df['player_dismissed'] = delivery_df['player_dismissed'].fillna("0")

#if column value is not zero mark it 1
delivery_df['player_dismissed'] = delivery_df['player_dismissed'].apply(lambda x:x if x == "0" else "1")

#changing datatype of column name
delivery_df['player_dismissed'] = delivery_df['player_dismissed'].astype('int')

#finding wickets using cumulative sum function
wickets = delivery_df.groupby('match_id')['player_dismissed'].cumsum()

#calculating wickets left by simple math operation
delivery_df['wickets_left'] = 10 - wickets
delivery_df

,match_id,city,winner,total_score,season,start_date,venue,innings,ball,batting_team,...,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,cricsheet_id,current_score,runs_left,over,balls_left,wickets_left
127,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,1,Mumbai Indians,...,NaN,0,NaN,NaN,1370352,0,234,1,119,10
128,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,2,Mumbai Indians,...,NaN,0,NaN,NaN,1370352,1,233,1,118,10
129,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,3,Mumbai Indians,...,NaN,0,NaN,NaN,1370352,1,233,1,117,10
130,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,4,Mumbai Indians,...,NaN,0,NaN,NaN,1370352,5,229,1,116,10
131,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,5,Mumbai Indians,...,caught,1,NaN,NaN,1370352,5,229,1,115,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168132,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,2,Kings XI Punjab,...,NaN,0,NaN,NaN,335983,193,48,19,10,6
168133,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,3,Kings XI Punjab,...,NaN,0,NaN,NaN,335983,194,47,19,9,6
168134,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,4,Kings XI Punjab,...,NaN,0,NaN,NaN,335983,195,46,19,8,6
168135,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,5,Kings XI Punjab,...,NaN,0,NaN,NaN,335983,197,44,19,7,6
168136,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,6,Kings XI Punjab,...,NaN,0,NaN,NaN,335983,198,43,19,6,6

In [187]:
#crr=current_runs/current_overs
delivery_df['crr'] = (delivery_df['current_score']*6)/(120 - delivery_df['balls_left'])
delivery_df.head()

,match_id,city,winner,total_score,season,start_date,venue,innings,ball,batting_team,...,player_dismissed,other_wicket_type,other_player_dismissed,cricsheet_id,current_score,runs_left,over,balls_left,wickets_left,crr
127,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,1,Mumbai Indians,...,0,NaN,NaN,1370352,0,234,1,119,10,0.0
128,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,2,Mumbai Indians,...,0,NaN,NaN,1370352,1,233,1,118,10,3.0
129,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,3,Mumbai Indians,...,0,NaN,NaN,1370352,1,233,1,117,10,2.0
130,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,4,Mumbai Indians,...,0,NaN,NaN,1370352,5,229,1,116,10,7.5
131,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,5,Mumbai Indians,...,1,NaN,NaN,1370352,5,229,1,115,9,6.0

In [188]:
#rrr=runs_left/over_left
delivery_df['rrr'] = (delivery_df['runs_left']*6)/delivery_df['balls_left']
delivery_df.head()

,match_id,city,winner,total_score,season,start_date,venue,innings,ball,batting_team,...,other_wicket_type,other_player_dismissed,cricsheet_id,current_score,runs_left,over,balls_left,wickets_left,crr,rrr
127,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,1,Mumbai Indians,...,NaN,NaN,1370352,0,234,1,119,10,0.0,11.798319
128,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,2,Mumbai Indians,...,NaN,NaN,1370352,1,233,1,118,10,3.0,11.847458
129,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,3,Mumbai Indians,...,NaN,NaN,1370352,1,233,1,117,10,2.0,11.948718
130,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,4,Mumbai Indians,...,NaN,NaN,1370352,5,229,1,116,10,7.5,11.844828
131,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,5,Mumbai Indians,...,NaN,NaN,1370352,5,229,1,115,9,6.0,11.947826

In [189]:
def result(row):
    return 1 if row['batting_team'] == row['winner'] else 0
delivery_df['result'] = delivery_df.apply(result,axis=1)

In [190]:
delivery_df

,match_id,city,winner,total_score,season,start_date,venue,innings,ball,batting_team,...,other_player_dismissed,cricsheet_id,current_score,runs_left,over,balls_left,wickets_left,crr,rrr,result
127,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,1,Mumbai Indians,...,NaN,1370352,0,234,1,119,10,0.000000,11.798319,0
128,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,2,Mumbai Indians,...,NaN,1370352,1,233,1,118,10,3.000000,11.847458,0
129,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,3,Mumbai Indians,...,NaN,1370352,1,233,1,117,10,2.000000,11.948718,0
130,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,4,Mumbai Indians,...,NaN,1370352,5,229,1,116,10,7.500000,11.844828,0
131,1370352,Ahmedabad,Gujarat Titans,234,2023,2023-05-26,"Narendra Modi Stadium, Ahmedabad",2,5,Mumbai Indians,...,NaN,1370352,5,229,1,115,9,6.000000,11.947826,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168132,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,2,Kings XI Punjab,...,NaN,335983,193,48,19,10,6,10.527273,28.800000,0
168133,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,3,Kings XI Punjab,...,NaN,335983,194,47,19,9,6,10.486486,31.333333,0
168134,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,4,Kings XI Punjab,...,NaN,335983,195,46,19,8,6,10.446429,34.500000,0
168135,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,5,Kings XI Punjab,...,NaN,335983,197,44,19,7,6,10.460177,37.714286,0
168136,335983,Chandigarh,Chennai Super Kings,241,2007/08,2008-04-19,"Punjab Cricket Association Stadium, Mohali",2,6,Kings XI Punjab,...,NaN,335983,198,43,19,6,6,10.421053,43.000000,0

In [191]:
required_data = delivery_df[['batting_team','bowling_team','city','runs_left','balls_left','wickets_left','total_score','crr','rrr','result']]

In [192]:
required_data

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,total_score,crr,rrr,result
127,Mumbai Indians,Gujarat Titans,Ahmedabad,234,119,10,234,0.000000,11.798319,0
128,Mumbai Indians,Gujarat Titans,Ahmedabad,233,118,10,234,3.000000,11.847458,0
129,Mumbai Indians,Gujarat Titans,Ahmedabad,233,117,10,234,2.000000,11.948718,0
130,Mumbai Indians,Gujarat Titans,Ahmedabad,229,116,10,234,7.500000,11.844828,0
131,Mumbai Indians,Gujarat Titans,Ahmedabad,229,115,9,234,6.000000,11.947826,0
...,...,...,...,...,...,...,...,...,...,...
168132,Kings XI Punjab,Chennai Super Kings,Chandigarh,48,10,6,241,10.527273,28.800000,0
168133,Kings XI Punjab,Chennai Super Kings,Chandigarh,47,9,6,241,10.486486,31.333333,0
168134,Kings XI Punjab,Chennai Super Kings,Chandigarh,46,8,6,241,10.446429,34.500000,0
168135,Kings XI Punjab,Chennai Super Kings,Chandigarh,44,7,6,241,10.460177,37.714286,0
168136,Kings XI Punjab,Chennai Super Kings,Chandigarh,43,6,6,241,10.421053,43.000000,0

In [193]:
#sampling Data
final_df = required_data.sample(required_data.shape[0])

In [194]:
final_df.sample()

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,total_score,crr,rrr,result
96001,Sunrisers Hyderabad,Chennai Super Kings,Chennai,140,65,8,210,7.636364,12.923077,0

In [195]:
#dropping null values
final_df.dropna(inplace=True)

In [196]:
#removing rows where balls_left=0 to remove -inf and inf from rrr column
final_df = final_df[final_df['balls_left']!=0]

In [197]:
#storing data in new csv
final_df.to_csv("final_data.csv",index=False)

In [198]:
final_df.head()

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,total_score,crr,rrr,result
108863,Rajasthan Royals,Mumbai Indians,Mumbai,137,80,6,167,4.500000,10.275000,0
93993,Sunrisers Hyderabad,Delhi Daredevils,Visakhapatnam,161,110,10,168,4.200000,8.781818,0
92314,Sunrisers Hyderabad,Mumbai Indians,Mumbai,90,69,8,158,8.000000,7.826087,0
164983,Kings XI Punjab,Deccan Chargers,Hyderabad,121,81,9,165,6.769231,8.962963,1
24317,Rajasthan Royals,Gujarat Titans,Mumbai,117,72,6,193,9.500000,9.750000,0

In [199]:
from sklearn.model_selection import train_test_split
X = final_df.iloc[:,:-1]
y = final_df.iloc[:,-1]
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [200]:
X_train

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,total_score,crr,rrr
28296,Gujarat Titans,Lucknow Super Giants,Mumbai,87,58,7,159,6.967742,9.000000
108842,Rajasthan Royals,Mumbai Indians,Mumbai,148,101,9,167,6.000000,8.792079
130487,Delhi Daredevils,Chennai Super Kings,Chennai,136,92,9,177,8.785714,8.869565
156156,Mumbai Indians,Deccan Chargers,Durban,158,101,9,169,3.473684,9.386139
65862,Sunrisers Hyderabad,Delhi Daredevils,Hyderabad,65,39,8,164,7.333333,10.000000
...,...,...,...,...,...,...,...,...,...
6350,Punjab Kings,Chennai Super Kings,Chennai,87,41,7,201,8.658228,12.731707
132180,Chennai Super Kings,Rajasthan Royals,Chennai,87,70,9,148,7.320000,7.457143
24057,Delhi Capitals,Royal Challengers Bangalore,Mumbai,134,86,9,190,9.882353,9.348837
89087,Mumbai Indians,Chennai Super Kings,Chennai,105,87,10,159,9.818182,7.241379
74741,Kings XI Punjab,Sunrisers Hyderabad,Chandigarh,133,66,7,208,8.333333,12.090909

In [201]:
X_test

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,total_score,crr,rrr
72908,Gujarat Lions,Kings XI Punjab,Chandigarh,99,67,10,190,10.301887,8.865672
136101,Mumbai Indians,Delhi Daredevils,Delhi,22,38,8,96,5.414634,3.473684
91231,Rajasthan Royals,Mumbai Indians,Mumbai,149,94,9,188,9.000000,9.510638
63640,Rajasthan Royals,Mumbai Indians,Mumbai,122,87,9,169,8.545455,8.413793
24887,Royal Challengers Bangalore,Chennai Super Kings,Mumbai,42,11,1,217,9.633028,22.909091
...,...,...,...,...,...,...,...,...,...
73885,Delhi Daredevils,Sunrisers Hyderabad,Delhi,29,20,6,186,9.420000,8.700000
125314,Royal Challengers Bangalore,Kings XI Punjab,Chandigarh,19,16,7,164,8.365385,7.125000
63468,Royal Challengers Bangalore,Kings XI Punjab,Indore,14,79,10,89,10.975610,1.063291
94239,Chennai Super Kings,Mumbai Indians,Mumbai,167,109,10,184,9.272727,9.192661
35810,Royal Challengers Bangalore,Chennai Super Kings,Mumbai,89,24,1,192,6.437500,22.250000

In [202]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

trf = ColumnTransformer([
    ('trf', OneHotEncoder(sparse_output=False, drop='first'), ['batting_team', 'bowling_team', 'city'])
], remainder='passthrough')

In [203]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
pipe = Pipeline(steps=[
    ('step1',trf),
    ('step2',LogisticRegression(solver='liblinear'))
])

In [204]:
pipe.fit(X_train,y_train)

C:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\compose\_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [205]:
Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [206]:
y_pred = pipe.predict(X_test)

In [207]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8009836286465001

In [208]:
pipe.predict_proba(X_test)[0]

array([0.00790605, 0.99209395])

In [209]:
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))

In [210]:
from sklearn.ensemble import RandomForestClassifier
trf = ColumnTransformer([
    ('trf',OneHotEncoder(sparse_output=False,drop='first'),['batting_team','bowling_team','city'])
],
remainder='passthrough')

pipe = Pipeline([
    ('step1',trf),
    ('step2',RandomForestClassifier())
])

pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
accuracy_score(y_test,y_pred)

0.9983157043724314

In [211]:
pipe.predict_proba(X_test)[0]

array([0.02, 0.98])

In [212]:
pickle.dump(pipe,open('pipe2.pkl','wb'))